-- Generated by scripts/generate_mygift_charges_seed.py
-- Source workbook: /Users/darrenchoong/Downloads/Printing Price Guide-OSSG Gift Rev01.xlsx
-- Row count: 142

insert into public.mygift_charges (
  vendor,
  charge_name,
  raw_item_name,
  item_codes,
  print_method,
  print_spec,
  position,
  raw_quantity,
  qty_min,
  qty_max,
  charge_type,
  charge_amount,
  unit,
  currency,
  gst_included,
  notes,
  source_doc,
  source_revision,
  effective_date,
  is_active
) values
  ('MYGIFT', 'Metal Pen (MP) / Plastic Pen (PP)', 'Metal Pen (MP)
/ Plastic Pen (PP)', array['MP', 'PP']::text[], 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 80.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Metal Pen (MP) / Plastic Pen (PP)', 'Metal Pen (MP)
/ Plastic Pen (PP)', array['MP', 'PP']::text[], 'silkscreen', '1 colour x 1 position', null, '50 - 300', 50, 300, 'flat_packet', 65.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Metal Pen (MP) / Plastic Pen (PP)', 'Metal Pen (MP)
/ Plastic Pen (PP)', array['MP', 'PP']::text[], 'silkscreen', '1 colour x 1 position', null, '301 - 499', 301, 499, 'per_piece_per_colour', 0.20, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Metal Pen (MP) / Plastic Pen (PP)', 'Metal Pen (MP)
/ Plastic Pen (PP)', array['MP', 'PP']::text[], 'silkscreen', '1 colour x 1 position', null, '500 - 999', 500, 999, 'per_piece_per_colour', 0.19, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Metal Pen (MP) / Plastic Pen (PP)', 'Metal Pen (MP)
/ Plastic Pen (PP)', array['MP', 'PP']::text[], 'silkscreen', '1 colour x 1 position', null, '1000 - 1499', 1000, 1499, 'per_piece_per_colour', 0.18, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Metal Pen (MP) / Plastic Pen (PP)', 'Metal Pen (MP)
/ Plastic Pen (PP)', array['MP', 'PP']::text[], 'silkscreen', '1 colour x 1 position', null, '1500 - 2999', 1500, 2999, 'per_piece_per_colour', 0.15, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Metal Pen (MP) / Plastic Pen (PP)', 'Metal Pen (MP)
/ Plastic Pen (PP)', array['MP', 'PP']::text[], 'silkscreen', '1 colour x 1 position', null, '3000 & Above', 3000, null, 'per_piece_per_colour', 0.14, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', array['SB', 'CR', 'AM', 'CE', 'VF']::text[], 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 60.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', array['SB', 'CR', 'AM', 'CE', 'VF']::text[], 'silkscreen', '1 colour x 1 position', null, '50 - 100', 50, 100, 'flat_packet', 40.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', array['SB', 'CR', 'AM', 'CE', 'VF']::text[], 'silkscreen', '1 colour x 1 position', null, '101 - 299', 101, 299, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', array['SB', 'CR', 'AM', 'CE', 'VF']::text[], 'silkscreen', '1 colour x 1 position', null, '300 - 499', 300, 499, 'per_piece_per_colour', 0.33, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', array['SB', 'CR', 'AM', 'CE', 'VF']::text[], 'silkscreen', '1 colour x 1 position', null, '500 - 799', 500, 799, 'per_piece_per_colour', 0.32, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', array['SB', 'CR', 'AM', 'CE', 'VF']::text[], 'silkscreen', '1 colour x 1 position', null, '800 - 1499', 800, 1499, 'per_piece_per_colour', 0.28, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', 'Bottle/ Auto Mug/ Ceramic Mug/ Food Container (SB/CR/AM/CE/ VF)', array['SB', 'CR', 'AM', 'CE', 'VF']::text[], 'silkscreen', '1 colour x 1 position', null, '1500 & Above', 1500, null, 'per_piece_per_colour', 0.26, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Small Premium Item (SF03/06/04/05/ MB18/ 24, NB/HL/KC/NH and etc)', 'Small Premium Item (SF03/06/04/05/ MB18/
24, NB/HL/KC/NH
and etc)', array['SF03', 'SF06', 'SF04', 'SF05', 'MB18', 'MB24', 'NB', 'HL', 'KC', 'NH']::text[], 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 60.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Small Premium Item (SF03/06/04/05/ MB18/ 24, NB/HL/KC/NH and etc)', 'Small Premium Item (SF03/06/04/05/ MB18/
24, NB/HL/KC/NH
and etc)', array['SF03', 'SF06', 'SF04', 'SF05', 'MB18', 'MB24', 'NB', 'HL', 'KC', 'NH']::text[], 'silkscreen', '1 colour x 1 position', null, '50 - 100', 50, 100, 'flat_packet', 40.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Small Premium Item (SF03/06/04/05/ MB18/ 24, NB/HL/KC/NH and etc)', 'Small Premium Item (SF03/06/04/05/ MB18/
24, NB/HL/KC/NH
and etc)', array['SF03', 'SF06', 'SF04', 'SF05', 'MB18', 'MB24', 'NB', 'HL', 'KC', 'NH']::text[], 'silkscreen', '1 colour x 1 position', null, '101 - 199', 101, 199, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Small Premium Item (SF03/06/04/05/ MB18/ 24, NB/HL/KC/NH and etc)', 'Small Premium Item (SF03/06/04/05/ MB18/
24, NB/HL/KC/NH
and etc)', array['SF03', 'SF06', 'SF04', 'SF05', 'MB18', 'MB24', 'NB', 'HL', 'KC', 'NH']::text[], 'silkscreen', '1 colour x 1 position', null, '200 - 299', 200, 299, 'per_piece_per_colour', 0.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Small Premium Item (SF03/06/04/05/ MB18/ 24, NB/HL/KC/NH and etc)', 'Small Premium Item (SF03/06/04/05/ MB18/
24, NB/HL/KC/NH
and etc)', array['SF03', 'SF06', 'SF04', 'SF05', 'MB18', 'MB24', 'NB', 'HL', 'KC', 'NH']::text[], 'silkscreen', '1 colour x 1 position', null, '300 - 499', 300, 499, 'per_piece_per_colour', 0.25, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Small Premium Item (SF03/06/04/05/ MB18/ 24, NB/HL/KC/NH and etc)', 'Small Premium Item (SF03/06/04/05/ MB18/
24, NB/HL/KC/NH
and etc)', array['SF03', 'SF06', 'SF04', 'SF05', 'MB18', 'MB24', 'NB', 'HL', 'KC', 'NH']::text[], 'silkscreen', '1 colour x 1 position', null, '500 - 999', 500, 999, 'per_piece_per_colour', 0.20, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Small Premium Item (SF03/06/04/05/ MB18/ 24, NB/HL/KC/NH and etc)', 'Small Premium Item (SF03/06/04/05/ MB18/
24, NB/HL/KC/NH
and etc)', array['SF03', 'SF06', 'SF04', 'SF05', 'MB18', 'MB24', 'NB', 'HL', 'KC', 'NH']::text[], 'silkscreen', '1 colour x 1 position', null, '1000 & Above', 1000, null, 'per_piece_per_colour', 0.18, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Umbrella (UM)', 'Umbrella (UM)', array['UM']::text[], 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 60.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Umbrella (UM)', 'Umbrella (UM)', array['UM']::text[], 'silkscreen', '1 colour x 1 position', null, '50 - 100', 50, 100, 'flat_packet', 40.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Umbrella (UM)', 'Umbrella (UM)', array['UM']::text[], 'silkscreen', '1 colour x 1 position', null, '101 - 299', 101, 299, 'per_piece_per_colour', 0.40, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Umbrella (UM)', 'Umbrella (UM)', array['UM']::text[], 'silkscreen', '1 colour x 1 position', null, '300 - 499', 300, 499, 'per_piece_per_colour', 0.38, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Umbrella (UM)', 'Umbrella (UM)', array['UM']::text[], 'silkscreen', '1 colour x 1 position', null, '500 - 799', 500, 799, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Umbrella (UM)', 'Umbrella (UM)', array['UM']::text[], 'silkscreen', '1 colour x 1 position', null, '800 - 1499', 800, 1499, 'per_piece_per_colour', 0.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Umbrella (UM)', 'Umbrella (UM)', array['UM']::text[], 'silkscreen', '1 colour x 1 position', null, '1500 & Above', 1500, null, 'per_piece_per_colour', 0.28, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Sunshade (SA20) for 1 side', 'Sunshade (SA20) for 1 side', array['SA20']::text[], 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 75.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Sunshade (SA20) for 1 side', 'Sunshade (SA20) for 1 side', array['SA20']::text[], 'silkscreen', '1 colour x 1 position', null, '50 - 100', 50, 100, 'flat_packet', 50.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Sunshade (SA20) for 1 side', 'Sunshade (SA20) for 1 side', array['SA20']::text[], 'silkscreen', '1 colour x 1 position', null, '101 - 199', 101, 199, 'per_piece_per_colour', 0.45, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Sunshade (SA20) for 1 side', 'Sunshade (SA20) for 1 side', array['SA20']::text[], 'silkscreen', '1 colour x 1 position', null, '200 - 499', 200, 499, 'per_piece_per_colour', 0.40, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Sunshade (SA20) for 1 side', 'Sunshade (SA20) for 1 side', array['SA20']::text[], 'silkscreen', '1 colour x 1 position', null, '500 - 999', 500, 999, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Sunshade (SA20) for 1 side', 'Sunshade (SA20) for 1 side', array['SA20']::text[], 'silkscreen', '1 colour x 1 position', null, '1000 & Above', 1000, null, 'per_piece_per_colour', 0.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Lanyard (LD)', 'Lanyard (LD)', array['LD']::text[], 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 60.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Lanyard (LD)', 'Lanyard (LD)', array['LD']::text[], 'silkscreen', '1 colour x 1 position', null, '50 - 100', 50, 100, 'flat_packet', 40.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Lanyard (LD)', 'Lanyard (LD)', array['LD']::text[], 'silkscreen', '1 colour x 1 position', null, '101 - 299', 101, 299, 'per_piece_per_colour', 0.40, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Lanyard (LD)', 'Lanyard (LD)', array['LD']::text[], 'silkscreen', '1 colour x 1 position', null, '300 - 499', 300, 499, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Lanyard (LD)', 'Lanyard (LD)', array['LD']::text[], 'silkscreen', '1 colour x 1 position', null, '500 - 999', 500, 999, 'per_piece_per_colour', 0.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Lanyard (LD)', 'Lanyard (LD)', array['LD']::text[], 'silkscreen', '1 colour x 1 position', null, '1000 & Above', 1000, null, 'per_piece_per_colour', 0.28, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Stress Ball (SA07/SA08)', 'Stress Ball (SA07/SA08)', array['SA07', 'SA08']::text[], 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 120.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Stress Ball (SA07/SA08)', 'Stress Ball (SA07/SA08)', array['SA07', 'SA08']::text[], 'silkscreen', '1 colour x 1 position', null, '50 - 150', 50, 150, 'flat_packet', 80.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Stress Ball (SA07/SA08)', 'Stress Ball (SA07/SA08)', array['SA07', 'SA08']::text[], 'silkscreen', '1 colour x 1 position', null, '151 - 299', 151, 299, 'per_piece_per_colour', 0.45, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Stress Ball (SA07/SA08)', 'Stress Ball (SA07/SA08)', array['SA07', 'SA08']::text[], 'silkscreen', '1 colour x 1 position', null, '300 - 499', 300, 499, 'per_piece_per_colour', 0.40, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Stress Ball (SA07/SA08)', 'Stress Ball (SA07/SA08)', array['SA07', 'SA08']::text[], 'silkscreen', '1 colour x 1 position', null, '500 - 999', 500, 999, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Stress Ball (SA07/SA08)', 'Stress Ball (SA07/SA08)', array['SA07', 'SA08']::text[], 'silkscreen', '1 colour x 1 position', null, '1000 & Above', 1000, null, 'per_piece_per_colour', 0.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Printing on Wristband / USB FAN (SA01/SA13/EP16 / EP17/EP18)', 'Printing on Wristband
/ USB FAN (SA01/SA13/EP16
/ EP17/EP18)', array['SA01', 'SA13', 'EP16', 'EP17', 'EP18']::text[], 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 60.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Printing on Wristband / USB FAN (SA01/SA13/EP16 / EP17/EP18)', 'Printing on Wristband
/ USB FAN (SA01/SA13/EP16
/ EP17/EP18)', array['SA01', 'SA13', 'EP16', 'EP17', 'EP18']::text[], 'silkscreen', '1 colour x 1 position', null, '50 - 100', 50, 100, 'flat_packet', 40.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Printing on Wristband / USB FAN (SA01/SA13/EP16 / EP17/EP18)', 'Printing on Wristband
/ USB FAN (SA01/SA13/EP16
/ EP17/EP18)', array['SA01', 'SA13', 'EP16', 'EP17', 'EP18']::text[], 'silkscreen', '1 colour x 1 position', null, '101 - 500', 101, 500, 'per_piece_per_colour', 0.38, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Printing on Wristband / USB FAN (SA01/SA13/EP16 / EP17/EP18)', 'Printing on Wristband
/ USB FAN (SA01/SA13/EP16
/ EP17/EP18)', array['SA01', 'SA13', 'EP16', 'EP17', 'EP18']::text[], 'silkscreen', '1 colour x 1 position', null, '501 - 1000', 501, 1000, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Printing on Wristband / USB FAN (SA01/SA13/EP16 / EP17/EP18)', 'Printing on Wristband
/ USB FAN (SA01/SA13/EP16
/ EP17/EP18)', array['SA01', 'SA13', 'EP16', 'EP17', 'EP18']::text[], 'silkscreen', '1 colour x 1 position', null, '1001 - 3000', 1001, 3000, 'per_piece_per_colour', 0.33, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Printing on Wristband / USB FAN (SA01/SA13/EP16 / EP17/EP18)', 'Printing on Wristband
/ USB FAN (SA01/SA13/EP16
/ EP17/EP18)', array['SA01', 'SA13', 'EP16', 'EP17', 'EP18']::text[], 'silkscreen', '1 colour x 1 position', null, '3001 & Above', 3001, null, 'per_piece_per_colour', 0.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Non Woven Bag (NW)', 'Non Woven Bag (NW)', array['NW']::text[], 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 60.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Non Woven Bag (NW)', 'Non Woven Bag (NW)', array['NW']::text[], 'silkscreen', '1 colour x 1 position', null, '50 - 130', 50, 130, 'flat_packet', 40.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Non Woven Bag (NW)', 'Non Woven Bag (NW)', array['NW']::text[], 'silkscreen', '1 colour x 1 position', null, '131 - 199', 131, 199, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Non Woven Bag (NW)', 'Non Woven Bag (NW)', array['NW']::text[], 'silkscreen', '1 colour x 1 position', null, '200 - 499', 200, 499, 'per_piece_per_colour', 0.25, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Non Woven Bag (NW)', 'Non Woven Bag (NW)', array['NW']::text[], 'silkscreen', '1 colour x 1 position', null, '500 - 999', 500, 999, 'per_piece_per_colour', 0.20, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Non Woven Bag (NW)', 'Non Woven Bag (NW)', array['NW']::text[], 'silkscreen', '1 colour x 1 position', null, '1000 & Above', 1000, null, 'per_piece_per_colour', 0.18, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bag - Nylon, Canvas, Jute', 'Bag - Nylon, Canvas, Jute', null, 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 60.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bag - Nylon, Canvas, Jute', 'Bag - Nylon, Canvas, Jute', null, 'silkscreen', '1 colour x 1 position', null, '50 - 100', 50, 100, 'flat_packet', 40.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bag - Nylon, Canvas, Jute', 'Bag - Nylon, Canvas, Jute', null, 'silkscreen', '1 colour x 1 position', null, '101 - 199', 101, 199, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bag - Nylon, Canvas, Jute', 'Bag - Nylon, Canvas, Jute', null, 'silkscreen', '1 colour x 1 position', null, '200 - 499', 200, 499, 'per_piece_per_colour', 0.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bag - Nylon, Canvas, Jute', 'Bag - Nylon, Canvas, Jute', null, 'silkscreen', '1 colour x 1 position', null, '500 - 999', 500, 999, 'per_piece_per_colour', 0.28, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Bag - Nylon, Canvas, Jute', 'Bag - Nylon, Canvas, Jute', null, 'silkscreen', '1 colour x 1 position', null, '1000 & Above', 1000, null, 'per_piece_per_colour', 0.25, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Backpack Bag/ Travelling Bag/ Trolley Bag', 'Backpack Bag/ Travelling Bag/ Trolley Bag', null, 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 70.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Backpack Bag/ Travelling Bag/ Trolley Bag', 'Backpack Bag/ Travelling Bag/ Trolley Bag', null, 'silkscreen', '1 colour x 1 position', null, '50 - 100', 50, 100, 'flat_packet', 45.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Backpack Bag/ Travelling Bag/ Trolley Bag', 'Backpack Bag/ Travelling Bag/ Trolley Bag', null, 'silkscreen', '1 colour x 1 position', null, '101 - 199', 101, 199, 'per_piece_per_colour', 0.45, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Backpack Bag/ Travelling Bag/ Trolley Bag', 'Backpack Bag/ Travelling Bag/ Trolley Bag', null, 'silkscreen', '1 colour x 1 position', null, '200 - 499', 200, 499, 'per_piece_per_colour', 0.40, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Backpack Bag/ Travelling Bag/ Trolley Bag', 'Backpack Bag/ Travelling Bag/ Trolley Bag', null, 'silkscreen', '1 colour x 1 position', null, '500 - 999', 500, 999, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Backpack Bag/ Travelling Bag/ Trolley Bag', 'Backpack Bag/ Travelling Bag/ Trolley Bag', null, 'silkscreen', '1 colour x 1 position', null, '1000 & Above', 1000, null, 'per_piece_per_colour', 0.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Hand Fan (SA12) - 1 Side', 'Hand Fan (SA12) - 1 Side', array['SA12']::text[], 'silkscreen', '1 colour x 1 position', null, '1 - 49', 1, 49, 'flat_packet', 70.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Hand Fan (SA12) - 1 Side', 'Hand Fan (SA12) - 1 Side', array['SA12']::text[], 'silkscreen', '1 colour x 1 position', null, '50 - 100', 50, 100, 'flat_packet', 45.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Hand Fan (SA12) - 1 Side', 'Hand Fan (SA12) - 1 Side', array['SA12']::text[], 'silkscreen', '1 colour x 1 position', null, '101 - 299', 101, 299, 'per_piece_per_colour', 0.40, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Hand Fan (SA12) - 1 Side', 'Hand Fan (SA12) - 1 Side', array['SA12']::text[], 'silkscreen', '1 colour x 1 position', null, '300 - 499', 300, 499, 'per_piece_per_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Hand Fan (SA12) - 1 Side', 'Hand Fan (SA12) - 1 Side', array['SA12']::text[], 'silkscreen', '1 colour x 1 position', null, '500 - 999', 500, 999, 'per_piece_per_colour', 0.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Hand Fan (SA12) - 1 Side', 'Hand Fan (SA12) - 1 Side', array['SA12']::text[], 'silkscreen', '1 colour x 1 position', null, '1000 - 1999', 1000, 1999, 'per_piece_per_colour', 0.25, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Hand Fan (SA12) - 1 Side', 'Hand Fan (SA12) - 1 Side', array['SA12']::text[], 'silkscreen', '1 colour x 1 position', null, '2000 & Above', 2000, null, 'per_piece_per_colour', 0.23, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Engraving on Wooden KeyChain', 'Engraving on Wooden KeyChain', null, 'engraving', 'engraving', null, '1 - 49', 1, 49, 'flat_packet', 80.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Engraving on Wooden KeyChain', 'Engraving on Wooden KeyChain', null, 'engraving', 'engraving', null, '50 - 100', 50, 100, 'flat_packet', 55.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Engraving on Wooden KeyChain', 'Engraving on Wooden KeyChain', null, 'engraving', 'engraving', null, '101 - 999', 101, 999, 'per_piece', 0.50, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Engraving on Wooden KeyChain', 'Engraving on Wooden KeyChain', null, 'engraving', 'engraving', null, '1000 & Above', 1000, null, 'per_piece', 0.45, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Engraving on Metal Item (MP, NH. TD, PB, Metal KC)', 'Engraving on Metal Item (MP, NH. TD, PB,
Metal KC)', array['MP', 'NH', 'TD', 'PB', 'KC']::text[], 'engraving', 'engraving', null, '1 - 49', 1, 49, 'flat_packet', 80.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Engraving on Metal Item (MP, NH. TD, PB, Metal KC)', 'Engraving on Metal Item (MP, NH. TD, PB,
Metal KC)', array['MP', 'NH', 'TD', 'PB', 'KC']::text[], 'engraving', 'engraving', null, '50 - 100', 50, 100, 'flat_packet', 55.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Engraving on Metal Item (MP, NH. TD, PB, Metal KC)', 'Engraving on Metal Item (MP, NH. TD, PB,
Metal KC)', array['MP', 'NH', 'TD', 'PB', 'KC']::text[], 'engraving', 'engraving', null, '101 - 499', 101, 499, 'per_piece', 0.50, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Engraving on Metal Item (MP, NH. TD, PB, Metal KC)', 'Engraving on Metal Item (MP, NH. TD, PB,
Metal KC)', array['MP', 'NH', 'TD', 'PB', 'KC']::text[], 'engraving', 'engraving', null, '500 - 999', 500, 999, 'per_piece', 0.45, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Engraving on Metal Item (MP, NH. TD, PB, Metal KC)', 'Engraving on Metal Item (MP, NH. TD, PB,
Metal KC)', array['MP', 'NH', 'TD', 'PB', 'KC']::text[], 'engraving', 'engraving', null, '1000 & Above', 1000, null, 'per_piece', 0.42, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Crystal Trophy', 'Crystal Trophy', null, 'uv_print', 'full colour', null, 'UV', 1, null, 'per_piece_full_colour', 7.00, 'piece', 'SGD', false, 'Special non-quantity row preserved from MYGIFT workbook.', 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Crystal Trophy', 'Crystal Trophy', null, 'engraving', 'engraving', null, 'Engraving', 1, null, 'per_piece', 7.00, 'piece', 'SGD', false, 'Special non-quantity row preserved from MYGIFT workbook.', 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Wood Plaque', 'Wood Plaque', null, 'uv_print', 'full colour', null, 'UV', 1, null, 'per_piece_full_colour', 9.00, 'piece', 'SGD', false, 'Special non-quantity row preserved from MYGIFT workbook.', 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Small Premium Item (PP/MP/NH/KC)', 'UV Print  - Small Premium Item
(PP/MP/NH/KC)', array['PP', 'MP', 'NH', 'KC']::text[], 'uv_print', 'full colour', null, '1 - 49', 1, 49, 'flat_packet', 120.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Small Premium Item (PP/MP/NH/KC)', 'UV Print  - Small Premium Item
(PP/MP/NH/KC)', array['PP', 'MP', 'NH', 'KC']::text[], 'uv_print', 'full colour', null, '50 - 180', 50, 180, 'flat_packet', 80.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Small Premium Item (PP/MP/NH/KC)', 'UV Print  - Small Premium Item
(PP/MP/NH/KC)', array['PP', 'MP', 'NH', 'KC']::text[], 'uv_print', 'full colour', null, '181 & Above', 181, null, 'per_piece_full_colour', 0.40, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - (Catering Equipment,', 'UV Print - (Catering
Equipment,', null, 'uv_print', 'full colour', null, '1 - 49', 1, 49, 'flat_packet', 120.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - (Catering Equipment,', 'UV Print - (Catering
Equipment,', null, 'uv_print', 'full colour', null, '50 - 100', 50, 100, 'flat_packet', 80.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - (Catering Equipment,', 'UV Print - (Catering
Equipment,', null, 'uv_print', 'full colour', null, '101 & Above', 101, null, 'per_piece_full_colour', 0.75, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Hand Fan 1 side', 'UV Print - Hand Fan 1 side', null, 'uv_print', 'full colour', null, '1 - 49', 1, 49, 'flat_packet', 150.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Hand Fan 1 side', 'UV Print - Hand Fan 1 side', null, 'uv_print', 'full colour', null, '50 - 100', 50, 100, 'flat_packet', 100.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Hand Fan 1 side', 'UV Print - Hand Fan 1 side', null, 'uv_print', 'full colour', null, '101 and above', 101, null, 'per_piece_full_colour', 0.80, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - (SA18/SA19/SA', 'UV Print -
(SA18/SA19/SA', null, 'uv_print', 'full colour', null, '1 - 10', 1, 10, 'flat_packet', 50.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - (SA18/SA19/SA', 'UV Print -
(SA18/SA19/SA', null, 'uv_print', 'full colour', null, '11 & Above', 11, null, 'per_piece_full_colour', 4.00, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Notebook/Pad (below 15cm(H))', 'UV Print -
Notebook/Pad (below 15cm(H))', array['BELO', 'W', 'W15', 'CM', 'H']::text[], 'uv_print', 'full colour', null, '1 - 49', 1, 49, 'flat_packet', 105.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Notebook/Pad (below 15cm(H))', 'UV Print -
Notebook/Pad (below 15cm(H))', array['BELO', 'W', 'W15', 'CM', 'H']::text[], 'uv_print', 'full colour', null, '50 - 100', 50, 100, 'flat_packet', 70.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Notebook/Pad (below 15cm(H))', 'UV Print -
Notebook/Pad (below 15cm(H))', array['BELO', 'W', 'W15', 'CM', 'H']::text[], 'uv_print', 'full colour', null, '101 & Above', 101, null, 'per_piece_full_colour', 0.60, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Notebook/Pad (above', 'UV Print - Notebook/Pad
(above', null, 'uv_print', 'full colour', null, '1 - 49', 1, 49, 'flat_packet', 150.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Notebook/Pad (above', 'UV Print - Notebook/Pad
(above', null, 'uv_print', 'full colour', null, '50 - 100', 50, 100, 'flat_packet', 100.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Notebook/Pad (above', 'UV Print - Notebook/Pad
(above', null, 'uv_print', 'full colour', null, '101 & Above', 101, null, 'per_piece_full_colour', 0.85, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - A4 Size (SA16)', 'UV Print - A4 Size (SA16)', array['SA16']::text[], 'uv_print', 'full colour', null, '1 - 49', 1, 49, 'flat_packet', 200.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - A4 Size (SA16)', 'UV Print - A4 Size (SA16)', array['SA16']::text[], 'uv_print', 'full colour', null, '50 - 100', 50, 100, 'flat_packet', 150.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - A4 Size (SA16)', 'UV Print - A4 Size (SA16)', array['SA16']::text[], 'uv_print', 'full colour', null, '101 & Above', 101, null, 'per_piece_full_colour', 1.20, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print Credit Card USB - 2', 'UV Print Credit
Card USB - 2', null, 'uv_print', 'full colour', null, '1 - 50', 1, 50, 'flat_packet', 100.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print Credit Card USB - 2', 'UV Print Credit
Card USB - 2', null, 'uv_print', 'full colour', null, '51 & Above', 51, null, 'per_piece_full_colour', 1.50, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Sport Bottle/Mug/Food Container (Full', 'UV Print - Sport
Bottle/Mug/Food Container (Full', null, 'uv_print', 'full colour', null, '1 - 49', 1, 49, 'flat_packet', 180.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Sport Bottle/Mug/Food Container (Full', 'UV Print - Sport
Bottle/Mug/Food Container (Full', null, 'uv_print', 'full colour', null, '50 - 299', 50, 299, 'per_piece_full_colour', 3.25, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'UV Print - Sport Bottle/Mug/Food Container (Full', 'UV Print - Sport
Bottle/Mug/Food Container (Full', null, 'uv_print', 'full colour', null, '300 & Above', 300, null, 'per_piece_full_colour', 3.00, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Heat Transfer on Ceramic Mug (CR01/CR02/ CR03/CR04/CR0', 'Heat Transfer on Ceramic Mug (CR01/CR02/
CR03/CR04/CR0', null, 'heat_transfer', 'full colour', null, '1 - 50', 1, 50, 'per_piece_full_colour', 1.50, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Heat Transfer on Ceramic Mug (CR01/CR02/ CR03/CR04/CR0', 'Heat Transfer on Ceramic Mug (CR01/CR02/
CR03/CR04/CR0', null, 'heat_transfer', 'full colour', null, '51 & Above', 51, null, 'per_piece_full_colour', 0.75, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Heat Transfer on Ceramic Mug (CR01/CR02/ CR03/CR04/CR0', 'Heat Transfer on Ceramic Mug (CR01/CR02/
CR03/CR04/CR0', null, 'heat_transfer', 'full colour', null, 'Individual Photo /Name (Add-on)', 1, null, 'add_on_per_piece', 2.20, 'piece', 'SGD', false, 'Add-on row from MYGIFT workbook.', 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print Acrylic KeyChain (KC06-KC09)', 'Paper Print Acrylic KeyChain
(KC06-KC09)', array['KC06', 'KC07', 'KC08', 'KC09']::text[], 'paper_print', 'full colour', null, '1 - 49', 1, 49, 'flat_packet', 120.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print Acrylic KeyChain (KC06-KC09)', 'Paper Print Acrylic KeyChain
(KC06-KC09)', array['KC06', 'KC07', 'KC08', 'KC09']::text[], 'paper_print', 'full colour', null, '50 - 99', 50, 99, 'flat_packet', 100.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print Acrylic KeyChain (KC06-KC09)', 'Paper Print Acrylic KeyChain
(KC06-KC09)', array['KC06', 'KC07', 'KC08', 'KC09']::text[], 'paper_print', 'full colour', null, '100 - 299', 100, 299, 'per_piece_full_colour', 0.50, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print Acrylic KeyChain (KC06-KC09)', 'Paper Print Acrylic KeyChain
(KC06-KC09)', array['KC06', 'KC07', 'KC08', 'KC09']::text[], 'paper_print', 'full colour', null, '300 - 499', 300, 499, 'per_piece_full_colour', 0.45, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print Acrylic KeyChain (KC06-KC09)', 'Paper Print Acrylic KeyChain
(KC06-KC09)', array['KC06', 'KC07', 'KC08', 'KC09']::text[], 'paper_print', 'full colour', null, '500 - 999', 500, 999, 'per_piece_full_colour', 0.40, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print Acrylic KeyChain (KC06-KC09)', 'Paper Print Acrylic KeyChain
(KC06-KC09)', array['KC06', 'KC07', 'KC08', 'KC09']::text[], 'paper_print', 'full colour', null, '1000 - 4999', 1000, 4999, 'per_piece_full_colour', 0.35, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print Acrylic KeyChain (KC06-KC09)', 'Paper Print Acrylic KeyChain
(KC06-KC09)', array['KC06', 'KC07', 'KC08', 'KC09']::text[], 'paper_print', 'full colour', null, '5000 - 9999', 5000, 9999, 'per_piece_full_colour', 0.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print Acrylic KeyChain (KC06-KC09)', 'Paper Print Acrylic KeyChain
(KC06-KC09)', array['KC06', 'KC07', 'KC08', 'KC09']::text[], 'paper_print', 'full colour', null, '10k & Above', 10000, null, 'per_piece_full_colour', 0.25, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print - Auto Mug (AM14, AM15)', 'Paper Print - Auto Mug (AM14, AM15)', array['AM14', 'AM15']::text[], 'paper_print', 'full colour', null, '50 - 99', 50, 99, 'per_piece_full_colour', 1.30, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print - Auto Mug (AM14, AM15)', 'Paper Print - Auto Mug (AM14, AM15)', array['AM14', 'AM15']::text[], 'paper_print', 'full colour', null, '100 - 199', 100, 199, 'per_piece_full_colour', 0.93, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print - Auto Mug (AM14, AM15)', 'Paper Print - Auto Mug (AM14, AM15)', array['AM14', 'AM15']::text[], 'paper_print', 'full colour', null, '200 - 299', 200, 299, 'per_piece_full_colour', 0.90, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print - Auto Mug (AM14, AM15)', 'Paper Print - Auto Mug (AM14, AM15)', array['AM14', 'AM15']::text[], 'paper_print', 'full colour', null, '300 - 399', 300, 399, 'per_piece_full_colour', 0.82, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print - Auto Mug (AM14, AM15)', 'Paper Print - Auto Mug (AM14, AM15)', array['AM14', 'AM15']::text[], 'paper_print', 'full colour', null, '400 - 499', 400, 499, 'per_piece_full_colour', 0.77, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Paper Print - Auto Mug (AM14, AM15)', 'Paper Print - Auto Mug (AM14, AM15)', array['AM14', 'AM15']::text[], 'paper_print', 'full colour', null, '500 & Above', 500, null, 'per_piece_full_colour', 0.75, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Epoxy on Metal KeyChain (KC/ ID01)', 'Epoxy on Metal KeyChain (KC/ ID01)', array['KC', 'ID01']::text[], 'epoxy', 'full colour', null, '1 - 49', 1, 49, 'flat_packet', 120.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Epoxy on Metal KeyChain (KC/ ID01)', 'Epoxy on Metal KeyChain (KC/ ID01)', array['KC', 'ID01']::text[], 'epoxy', 'full colour', null, '50 - 100', 50, 100, 'flat_packet', 80.00, 'packet', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Epoxy on Metal KeyChain (KC/ ID01)', 'Epoxy on Metal KeyChain (KC/ ID01)', array['KC', 'ID01']::text[], 'epoxy', 'full colour', null, '101 - 200', 101, 200, 'per_piece_full_colour', 0.75, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Epoxy on Metal KeyChain (KC/ ID01)', 'Epoxy on Metal KeyChain (KC/ ID01)', array['KC', 'ID01']::text[], 'epoxy', 'full colour', null, '201 - 300', 201, 300, 'per_piece_full_colour', 0.70, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Epoxy on Metal KeyChain (KC/ ID01)', 'Epoxy on Metal KeyChain (KC/ ID01)', array['KC', 'ID01']::text[], 'epoxy', 'full colour', null, '301 - 500', 301, 500, 'per_piece_full_colour', 0.65, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Epoxy on Metal KeyChain (KC/ ID01)', 'Epoxy on Metal KeyChain (KC/ ID01)', array['KC', 'ID01']::text[], 'epoxy', 'full colour', null, '501 - 700', 501, 700, 'per_piece_full_colour', 0.58, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Epoxy on Metal KeyChain (KC/ ID01)', 'Epoxy on Metal KeyChain (KC/ ID01)', array['KC', 'ID01']::text[], 'epoxy', 'full colour', null, '701 - 800', 701, 800, 'per_piece_full_colour', 0.55, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Epoxy on Metal KeyChain (KC/ ID01)', 'Epoxy on Metal KeyChain (KC/ ID01)', array['KC', 'ID01']::text[], 'epoxy', 'full colour', null, '801 - 900', 801, 900, 'per_piece_full_colour', 0.53, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', 'Epoxy on Metal KeyChain (KC/ ID01)', 'Epoxy on Metal KeyChain (KC/ ID01)', array['KC', 'ID01']::text[], 'epoxy', 'full colour', null, '900 - 1000', 900, 1000, 'per_piece_full_colour', 0.50, 'piece', 'SGD', false, null, 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', '*NW17 add S$0.05/pc from above price', '*NW17 add S$0.05/pc from above price', array['NW17']::text[], 'silkscreen', '1 colour x 1 position', null, 'add S$0.05/pc from above price', 1, null, 'add_on_per_piece', 0.05, 'piece', 'SGD', false, 'Apply in addition to Non Woven Bag price for NW17.', 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true),
  ('MYGIFT', '*Below is Full Colour Printing Method Except metallic Gold & Silver', '*Below is Full Colour Printing Method Except
metallic Gold & Silver', null, null, null, null, 'note', 0, null, 'note', 0.00, 'note', 'SGD', false, 'Full colour printing method section note; metallic gold and silver excluded.', 'Printing Price Guide - OSSG Gift Rev01', 'Rev01', null, true)
on conflict do nothing;
